### ISSUE TITLE
Serve up streamium.io via https instead of http

### ISSUE THREAD

**Issue by jrabek** [streamium/streamium#101]
Not only does this make the user feel more secure since a financial transaction is involved, but it also will cause the browser to remember that the user allowed streamium.io access to the camera.  This way the user doesn't have to click on the "Allow access to camera and microphone" every time they use the site.

**Comment by jrabek** [comment]
It will mean you will need a cert, but the certs aren't too expensive.

**Comment by eordano** [comment]
https://streamium.io

Now redirecting http -> https

Thanks!
