### ISSUE TITLE
"Channel name taken" error on Windows/Chrome

### ISSUE THREAD

**Issue by batalles** [streamium/streamium#128]

**Comment by kvnn** [comment]
This error appears for any exception caught in [StreamiumProvider.init](https://github.com/streamium/streamium/blob/master/app/provider/provider.js#L35). Might you have an incorrect number entered into Price Rate?

**Comment by kvnn** [comment]
Unless @batalles can verify otherwise, this is most likely a duplicate of https://github.com/streamium/streamium/issues/133

**Comment by eordano** [comment]
Dupe
