### ISSUE TITLE
"Channel name is taken" error is returned inappropriately 

### ISSUE THREAD

**Issue by kvnn** [streamium/streamium#133]
"Channel name is taken, please pick a different one" UI error is given for any error that is raised in [StreamiumProvider.init](https://github.com/streamium/streamium/blob/master/app/provider/provider.js#L35) from [$scope.submit](https://github.com/streamium/streamium/blob/master/app/provider/provider.js#L35).

I'm happy to push up a fix for this today.

**Comment by maraoz** [comment]
fixed in https://github.com/streamium/streamium/pull/130
