### ISSUE TITLE
Improve wording of error messages

### ISSUE THREAD

**Issue by demibrener** [streamium/streamium#162]
Make them more user friendly.

**Comment by maraoz** [comment]
Here are some errors that need fixing:

![screenshot from 2015-06-08 14 35 08](https://cloud.githubusercontent.com/assets/287189/8041038/ae041e7c-0deb-11e5-8e81-e5ec7b66d36d.png)

![screenshot from 2015-06-08 14 38 07](https://cloud.githubusercontent.com/assets/287189/8041085/014da314-0dec-11e5-8806-806f6d2c79c8.png)


(see https://github.com/streamium/streamium/blob/master/app/provider/controller.js#L97)



And this:
![screenshot from 2015-06-08 14 59 32](https://cloud.githubusercontent.com/assets/287189/8041504/02bbb4e0-0def-11e5-8bbd-5baf5b760b7f.png)

See: https://github.com/streamium/streamium/blob/59a44cfc382babb7480191c8bb652577ef91a74d/app/client/controller.js#L55
