### ISSUE TITLE
Bug: rounding error in generated qr code

### ISSUE THREAD

**Issue by robvanbentem** [streamium/streamium#164]
In certain generated qr codes there is an invalid url behind a qr code. At least I think it's invalid since my Mycelium wallet does not recognize it as a valid format.

After investigating it further I found out there is a rounding error in the amount param.

Here's an [example](http://i.imgur.com/ld1LbQh.png).

As you can see it's also visible in the ui but not in the link behind it.

**Comment by maraoz** [comment]
Thanks for reporting!!!
